const LOAD_IMG_COMPLETE = 'LOAD_IMG_COMPLETE';
const LOAD_IMG_FAIL = 'LOAD_IMG_FAIL';
const ITEM_ANIMATION_CLASS = 'viewer-animation';
const LOCK_NAME = 'STOP_SWIPE';
const LEFT_IMG = -1;
const CENTER_IMG = 0;
const RIGHT_IMG = 1;

export {
    LOAD_IMG_COMPLETE,
    LOAD_IMG_FAIL,
    LOCK_NAME,
    ITEM_ANIMATION_CLASS,
    LEFT_IMG,
    CENTER_IMG,
    RIGHT_IMG
};
